// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SentMailProject.Models.Context;

namespace SentMailProject.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221015093826_mig-one-to-one")]
    partial class migonetoone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SentMailProject.Models.Context.Sender", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("Senders");
                });

            modelBuilder.Entity("SentMailProject.Models.Context.SentMail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReadStatus")
                        .HasColumnType("bit");

                    b.Property<int>("SenderID")
                        .HasColumnType("int");

                    b.Property<bool>("SenderStarred")
                        .HasColumnType("bit");

                    b.Property<bool>("SenderStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToWhoID")
                        .HasColumnType("int");

                    b.Property<bool>("ToWhoStarred")
                        .HasColumnType("bit");

                    b.Property<bool>("ToWhoStatus")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("SenderID")
                        .IsUnique();

                    b.HasIndex("ToWhoID")
                        .IsUnique();

                    b.ToTable("SentMails");
                });

            modelBuilder.Entity("SentMailProject.Models.Context.ToWho", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("ToWhos");
                });

            modelBuilder.Entity("SentMailProject.Models.Context.SentMail", b =>
                {
                    b.HasOne("SentMailProject.Models.Context.Sender", "Sender")
                        .WithOne("SentMail")
                        .HasForeignKey("SentMailProject.Models.Context.SentMail", "SenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SentMailProject.Models.Context.ToWho", "ToWho")
                        .WithOne("SentMail")
                        .HasForeignKey("SentMailProject.Models.Context.SentMail", "ToWhoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("ToWho");
                });

            modelBuilder.Entity("SentMailProject.Models.Context.Sender", b =>
                {
                    b.Navigation("SentMail");
                });

            modelBuilder.Entity("SentMailProject.Models.Context.ToWho", b =>
                {
                    b.Navigation("SentMail");
                });
#pragma warning restore 612, 618
        }
    }
}
